sudo: required

services:
  - docker

cache:
  directories:
    - .build

before_install:
  - docker pull nmhnmh/sitekicker
  - docker run --rm -v "$TRAVIS_BUILD_DIR:/source" nmhnmh/sitekicker 

script:
  - echo "Done"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: nmhnmh/nmhnmh.github.io
  local_dir: .build
  target_branch: master
  email: niminghao804@gmail.com
  name: Minghao Ni
  on:
    branch: master
